// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc3to4qDHXLuBSNX181mMTTgPA6FKJFPQ',
    appId: '1:413821381246:web:8bc6f4a8646394e267062f',
    messagingSenderId: '413821381246',
    projectId: 'quiz-records-68b7d',
    authDomain: 'quiz-records-68b7d.firebaseapp.com',
    databaseURL: 'https://quiz-records-68b7d-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-records-68b7d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8BrfeqlAnmj10jdp23EmXIj20eidDY4',
    appId: '1:413821381246:android:b30d04bd22bc1e5967062f',
    messagingSenderId: '413821381246',
    projectId: 'quiz-records-68b7d',
    databaseURL: 'https://quiz-records-68b7d-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-records-68b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf6FP7sPeVgzJC1b2NN1AgGWuDzWGE3Qo',
    appId: '1:413821381246:ios:fa6a4ebc7313632c67062f',
    messagingSenderId: '413821381246',
    projectId: 'quiz-records-68b7d',
    databaseURL: 'https://quiz-records-68b7d-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-records-68b7d.appspot.com',
    iosBundleId: 'com.example.quizRecords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf6FP7sPeVgzJC1b2NN1AgGWuDzWGE3Qo',
    appId: '1:413821381246:ios:6b9b8b6cfb40867067062f',
    messagingSenderId: '413821381246',
    projectId: 'quiz-records-68b7d',
    databaseURL: 'https://quiz-records-68b7d-default-rtdb.firebaseio.com',
    storageBucket: 'quiz-records-68b7d.appspot.com',
    iosBundleId: 'com.example.quizRecords.RunnerTests',
  );
}
